### ISSUE TITLE
Complete initial PDS App Bar widget for simple web deployment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds#3]
@c-suh has already put a lot of work into a simple PDS App Bar that functions similarly to the [Feedback Widget](https://github.com/NASA-PDS/feedback-widget) with minimal overhead to deploy at each of the nodes.

Here are some tasks I see remaining with the [current widget deployed at pds.nasa.gov](https://github.com/NASA-PDS/feedback-widget) (these will need individual tickets defined once these tasks are solidified):
* Migrate app bar widget to public github
* Document how a node can deploy this widget
* Work with DNs to deploy widget as appropriate

**Rationale**
Note: This has been bumped up in priority per conversations with Project Office.

**Comment by edwardbarraza** [comment]
Things to consider in the PDS app bar above what is already deployed

- Log in button (primary) for user authentication
- Settings icon (cog) for user settings (preferences, theme toggle)
- Cart for products?

**Comment by c-suh** [comment]
Initial thoughts:
- move question mark to the left of 'Find a Node'
- insert two icons in upper right for Login and Cart
- have icon for Settings included in the dropdown for Login

**Comment by jordanpadams** [comment]
per meeting today:

updates needed:
- [ ] move app bar to Github public repo (https://github.com/NASA-PDS/pds-wds-web)
- [ ] move question mark to the left of 'Find a Node'
- [ ] update the icon with grayscale version (to be provided by @edwardbarraza )
- [ ] remove bolding from P, D, S in spelling
- [ ] removing NASA from "NASA Planetary Data System"
- [ ] update colors to match current WDS color schemes (to be provided by @edwardbarraza )
- [ ] update height, dimensions, and spacing to match current WDS (to be provided by @edwardbarraza )
- [ ] update typography to match current WDS (to be provided by @edwardbarraza )
- [ ] check app bar break points for mobile (to be provided by @edwardbarraza )
- [ ] Document how a node can deploy this widget

punt to next delivery:
* light / dark / settings / login
* see-through app bar

**Comment by edwardbarraza** [comment]
Here is the icon in png format. It should be sized at 48 x 25 in the app bar.
![PDSgrayscale](https://user-images.githubusercontent.com/26258411/93275945-2a3a8780-f773-11ea-84df-c606901217c0.png)

**Comment by edwardbarraza** [comment]
<img width="1440" alt="PDS app bar" src="https://user-images.githubusercontent.com/26258411/93366426-fb1e2780-f7ff-11ea-8176-3812d175ff09.png">

**Comment by edwardbarraza** [comment]
[Figma design file](https://www.figma.com/file/Sr1NxgRuxhTfHNncuCMV7y/Engineering-Node?node-id=580%3A4) has been shared with @c-suh and @eddiesarevalo  - the page of interest is labeled App Bar 1.0

**Comment by edwardbarraza** [comment]
<img width="165" alt="info" src="https://user-images.githubusercontent.com/26258411/93378757-c7e49400-f811-11ea-8fd6-f244df1e9dff.png">
 'Info' icon from the design system

**Comment by c-suh** [comment]
@edwardbarraza I'll send you a link to the changes; let me know if I've missed anything.

**Comment by tloubrieu-jpl** [comment]
@c-suh is waiting for feedback from @edwardbarraza

**Comment by edwardbarraza** [comment]
The `i` icon currently has the following text in tooltip:
`Welcome to NASA's PDS

NASA's Planetary Data System (PDS) maintains and archives data from planetary missions dated from the beginning of space exploration through the concerted effort of nine teams geographically distributed around the U.S.

This bar indicates that you are within the PDS enterprise which includes 6 science discipline nodes and 2 support nodes which are overseen by the Project Management Office at NASA's Goddard Space Flight Center (GSFC). Each node is led by an expert in the subject discipline, supported by an advisory group of other practitioners of that discipline, and subject to selection and approval under a regular NASA Research Announcement.

Find a Node - Use these links to navigate to any of the 8 publicly accessible PDS Nodes.`

We have moved the tooltip next to the `Find a Node` dropdown and have created an association with that feature, so I say we ax the first bit of the tooltip text and just keep this:

`Find a Node - Use these links to navigate to any of the 8 publicly accessible PDS Nodes.

This bar indicates that you are within the PDS enterprise which includes 6 science discipline nodes and 2 support nodes which are overseen by the Project Management Office at NASA's Goddard Space Flight Center (GSFC). Each node is led by an expert in the subject discipline, supported by an advisory group of other practitioners of that discipline, and subject to selection and approval under a regular NASA Research Announcement.`

Tooltips should be short and informative - what we have is overly verbose. WDY think @jordanpadams?

**Comment by jordanpadams** [comment]
@edwardbarraza looks good!

**Comment by c-suh** [comment]
Other change requested but not on Figma:
- [x]  have information show on hover, not select.
- [ ]  hover should be persistent (on info body and icon)
- [x]  info body shall show on top of the dropdown

**Comment by c-suh** [comment]
@edwardbarraza and @jordanpadams please verify the gamma version before I push the changes.

**Comment by edwardbarraza** [comment]
Looks good! ✅

**Comment by c-suh** [comment]
Updates specified in the [comment](https://github.com/NASA-PDS/pds-wds/issues/3#issuecomment-686787913) above have been made operational. Changes will be pushed to a TBD repository.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams should we create a new repository for the app bar Catherine worked on ?

**Comment by c-suh** [comment]
@tloubrieu-jpl apologies for not updating the comment. The updates have been pushed to an existing repository and packaged as release [PDS WDS Web v0.0.1](https://github.com/NASA-PDS/pds-wds-web/releases/tag/0.0.1)

**Comment by tariqksoliman** [comment]
Hi! This is awesome. Two minor things to note too:
1. The info icon is better as an svg:
```
<svg style="width:17px;height:17px;/* display: none; */" viewBox="0 0 24 24">
    <path fill="white" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
</svg>
```
2. The `pds-app-bar-dropdown` ul uses the default user agent margin style and so sits below the app bar 16px by default.


Also, if sites were to implement informational banners, should those sit above or below the app bar?

**Comment by edwardbarraza** [comment]
I am happy to provide an SVG here, only Github doesn't support that type of file. Ideas?

Regarding informational banners, we haven't discussed what the informational banner would look like, but we should distinguish between PDS-wide banner style/placement and Node-Specific style/placement. TBD.

**Comment by jordanpadams** [comment]
@edwardbarraza upload here as a ZIP. @c-suh can you make the quick update when you have a chance?

**Comment by edwardbarraza** [comment]
[info_icon.zip](https://github.com/NASA-PDS/pds-wds/files/5278204/info_icon.zip)

**Comment by tariqksoliman** [comment]
The svg above can be inline.

**Comment by tariqksoliman** [comment]
It's also good practice to include the attribute `rel="noopener"` on all the anchor links with `target="_blank"` as it stops the target page from referencing the previous page.

**Comment by tariqksoliman** [comment]
Oh, one other little thing worth looking into too (that the Earth daacs miss) is that, because the app bar renders after the page loads, the whole rest of the page jumps down suddenly (constantly refresh to see this more clearly). 

A quick way to solve this is to require nodes that wish to load this way to also add something like:
`<div id="pds-app-bar" style="width: 100%; height: 35px; background: black;"><div/>`
to the top of their page to then populate it later.

**Comment by c-suh** [comment]
Hi @tariqksoliman. Thank you for your suggestions! We have started to address them, and you will be able to track the status of these at the [pds-wds-web](https://github.com/NASA-PDS/pds-wds-web/issues) repo.

Further suggestions or comments - the detailed the better - would be greatly appreciated there. Thank you for helping us (streamline the process to) improve this app bar!

**Comment by tloubrieu-jpl** [comment]
Initial development has been released
