### ISSUE TITLE
Updated header components

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#55]
The title and navbar components need additional polish and work.

- [x] Migration of component into `wds-react` package
- [ ] Further style improvements to improve alignment with Figma design
- [x] Implement menu systems
- [x] Update Iconography

**Comment by tloubrieu-jpl** [comment]
@anilnatha is making progress on this ticket.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is migrating the component to wds-react repository. The tests are made a second application which calls this component.

**Comment by eddiesarevalo** [comment]
Breaking out this ticket into an epic.

**Comment by nutjob4life** [comment]
Eddie's branching out with Anil to discuss a bigger issue: styles from Web Design System into our own components in a maintainable way. Current way is too messy. Will become more difficult down the line. Researched CSS modules as a possible solution—but too confusing. Good solution: use plain CSS and material class names. Will feedback with Anil. Mike also asked if we'll need to support themes. If Anil's good, will update header styles. Will switch rest of component library on agreed-upon method.

**Comment by eddiesarevalo** [comment]
@anilnatha 
Pull request for wds-react https://github.com/NASA-PDS/wds-react/pull/24
Pull request for wds https://github.com/NASA-PDS/wds/pull/19
