### ISSUE TITLE
Phase 1: Search Implementation

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds#58]
Implement the PDS Serach Page based off our MVP design captured in Figma.

The components that will be needed for this page are listed as follows (will be broken out into separate tickets for tracking).
- [x] Results Counter
- [x] Search Input
- [x] Search Results List
- [x] Search Filters
- [x] Search Actions
- [x] Search Results Pagination
- [x] Empty/No Results State

Other tasks that are included.
- [x] Set up page layout
- [x] Connect search input to API.
- [x] Responsiveness for all components and layout.

Make updates to wds-react components for new design changes.
- [x] Text field

Figma designs at: https://www.figma.com/design/Gi5Cy9DFEhqY2VkhYkOQCD/Final-Designs?node-id=1125-184331&t=8uWswXuvg4np6FfI-0

**Comment by jordanpadams** [comment]
📆 01/2024 status: Deferring these landing pages to next build. This website delivery spans several builds, so no impact on delivery. No review from SWG needed.

**Comment by tloubrieu-jpl** [comment]
New designs expected for product types.

**Comment by eddiesarevalo** [comment]
Merged in https://github.com/NASA-PDS/portal-wp/pull/20
